### ISSUE TITLE
Preview not working using list mode

### ISSUE THREAD

**Issue by CimplexAB** [jesperweber/Our.Umbraco.HeadlessPreview#4]
**Which HeadlessPreview version are you using? (Please write the *exact* version, example: 2.0.0)**
2.2.0

**Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)**
13.4.1

**Describe the bug**
The preview button is not replaced on when list mode is activated

**To Reproduce**
Create a parent and some child nodes, activate list mode on parent.

**Expected behavior**
The preview button should be replaced.

**Screenshots**
![image](https://github.com/user-attachments/assets/f90f1c6e-1ecd-4604-8155-22933c113e3e)

**Additional context**
It looks like it works if you remove "isLoading" from this line of code:
https://github.com/jesperweber/Our.Umbraco.HeadlessPreview/blob/b89b504cdb8a99c7c3d5a9091e8eb2492d585667/src/Our.Umbraco.HeadlessPreview/App_Plugins/Our.Umbraco.HeadlessPreview/js/headlessPreview.service.js#L47

**Comment by jesperweber** [comment]
Hi @CimplexAB, thanks for reporting this, and yes I can reproduce the issue as well. 

I don't think the issue is specific to list mode pages though, but if the `getPreviewMode` endpoint is to slow, the `if` statement you mentioned is evaluated before the loading is complete and the headlessPreview doesn't trigger.

I reprocessed it by adding a sleep timer of 1 second in the endpoint to simulate a slow response from the API.

I'll create a fix for it 😊

**Comment by jesperweber** [comment]
Here's a PR with a fix. You can copy the `headlessPreview.service.js` file to your installation to see if it works. 
https://github.com/jesperweber/Our.Umbraco.HeadlessPreview/pull/5

**Comment by CimplexAB** [comment]
> Here's a PR with a fix. You can copy the `headlessPreview.service.js` file to your installation to see if it works. #5

Hi bud! Looks great, tested in two different list views and they both work like a charm! 

H5YR!

**Comment by jesperweber** [comment]
Great :-)

A new version 2.2.1 with the fix has now been released. Once again, thanks for reporting and help with debug and test 🙏
